version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./docker/db/confd:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
    env_file: 
      ./.env
    ports:
      - 3306:3306
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    volumes:
      - ./app:/app
      - installed_gems:/app/vendor/bundle
    tty: true

volumes:
  db_data:
  installed_gems:
